[[commands]]
name="/about"
description="Tells you information about the bot"
example="/about"
permission="Everyone"

[[commands]]
name="/add"
description="Adds a user to a ticket"
example="/add @User #ticket"
permission="Everyone"

[[commands]]
name="/addadmin"
description="Grants a user or role admin privileges"
example="/addadmin @User"
permission="Administrator"

[[commands]]
name="/addsupport"
description="Adds a user or role as a support representative"
example="/addsupport @User"
permission="Administrator"

[[commands]]
name="/blacklist"
description="Toggles whether users are allowed to interact with the bot"
example="/blacklist @User"
permission="Support"

[[commands]]
name="/cancel"
description="Cancels the setup process"
example="/cancel"
permission="Administrator"

[[commands]]
name="/claim"
description="Assigns a single staff member to a ticket"
example="/claim"
permission="Support"

[[commands]]
name="/close"
description="Closes the current ticket"
example="/close"
permission="Everyone"

[[commands]]
name="/help"
description="Shows you a list of commands"
example="/help"
permission="Everyone"

[[commands]]
name="/mt"
description="Command for managing tags"
example="/mcr [list/add/delete]"
permission="Support"

[[commands]]
name="/open"
description="Opens a new ticket"
example="/open"
permission="Everyone"

[[commands]]
name="/panel"
description="Creates a panel to enable users to open a ticket with 1 click"
example="/panel"
permission="Administrator"

[[commands]]
name="/remove"
description="Removes a user from a ticket"
example="/remove"
permission="Everyone"

[[commands]]
name="/removeadmin"
description="Revokes a user's or role's admin privileges"
example="/removeadmin @User"
permission="Administrator"

[[commands]]
name="/removesupport"
description="Revokes a user's or role's support representative privileges"
example="/removesupport @User"
permission="Administrator"

[[commands]]
name="/rename"
description="Renames the current ticket"
example="/rename channel-name"
permission="Support"

[[commands]]
name="/setup"
description="Allows you to easily configure the bot"
example="/setup"
permission="Administrator"

[[commands]]
name="/stats"
description="Shows you statistics about users, support staff and the server"
example="/stats [server / @User]"
permission="Support"

[[commands]]
name="/tag"
description="Sends a predefined snippet of text"
example="/tag mytag"
permission="Support"

[[commands]]
name="/transfer"
description="Transfers a claimed ticket to another user"
example="/transfer @User"
permission="Support"

[[commands]]
name="/unclaim"
description="Removes the claim on the current ticket"
example="/unclaim"
permission="Support"

[[commands]]
name="/viewstaff"
description="Lists the staff members and roles"
example="/viewstaff"
permission="Everyone"

[[commands]]
name="/vote"
description="Gives you a link to vote for free premium"
example="/vote"
permission="Everyone"
