version: 2
jobs:
  build:
    docker:
      - image: golang:1.14-alpine
    working_directory: /go/src/github.com/TicketsBot/Website

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go build cmd/website/main.go

      - store_artifacts:
          path: /go/src/github.com/TicketsBot/Website/main